apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spractise-deployment
spec:
  selector:
    matchLabels:
      app: k8spractise-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: k8spractise-deployment
    spec:
      containers:
        - name: k8spractise-deployment
          image: magdamag/k8spractise:v1.0.0
          ports:
            - containerPort: 3000
         