apiVersion: v1
kind: Service
metadata:
  name: k8spractise-service
spec:
  selector:
    app: k8spractise-deployment
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3723
      targetPort: 3000
      nodePort: 31000